site_name: My Documentation Site
theme:
  name: mkdocs
nav:
  - Home: index.md
  - File Level Metadata: file_level_metadata.md
  - Package Level Metadata: package_level_metadata.md
  - Register to Submit: register_to_submit.md
  - Submit Online: submit_online.md
