site_name: Smithsonian Tropical Data Portal Documentation
docs_dir: docs
site_url: https://legbrisse.github.io/STDP_Documentation/
theme:
  name: material
nav:
  - Home: index.md
  - Register to Submit: register_to_submit.md
  - Submit Online: submit_online.md
  - Package Level Metadata: package_level_meta_reqs.md
  - File Level Metadata: file_level_metadata.md
  - Frequently Asked Questions: faq.md
  

extra_css:
  - css/custom.css